### ISSUE TITLE
can't copy in the betwixt

### ISSUE THREAD

**Issue by desenmeng** [kdzwinel/betwixt#35]
Thanks for this awesome project.

I found I can't copy anything in the app.

**Comment by kdzwinel** [comment]
Thanks for reporting!

Please let me know:
- what OS are you running
- which version of Betwixt (1.0.0 was just released)
- what exactly can't you copy?

On OSX, running Betwix v1.0.0 I can copy everything from the Headers and Preview/Response section just fine.

**Comment by desenmeng** [comment]
OSX version: 10.11.4
Betwixt version: 1.0.0

![qq20160323-0](https://cloud.githubusercontent.com/assets/1209159/13973784/64276eec-f0e1-11e5-9b66-bc58c63ce199.png)

With command + c, I can't copy the selected url.

**Comment by kdzwinel** [comment]
I'm able to reproduce it.

Notes:
- It happens when running `Betwix.app` and does not happen when running from sources (`npm start`). 
- Until it's fixed, please use context menu:

<img width="358" alt="screen shot 2016-03-28 at 02 38 47" src="https://cloud.githubusercontent.com/assets/985504/14068784/4a2033fc-f48e-11e5-876a-bfc75a8145e9.png">
- possible fix: https://pracucci.com/atom-electron-enable-copy-and-paste.html

**Comment by desenmeng** [comment]
Thanks @kdzwinel

**Comment by kdzwinel** [comment]
Bug was fixed in [v1.3.0](https://github.com/kdzwinel/betwixt/releases/tag/1.3.0). Enjoy!

**Comment by desenmeng** [comment]
:+1:  @kdzwinel
